version: '2'
services:
  # 基本环境
  php: # 容器名字
    # build 该置顶目录下的dockerfile
    build: .
    # image指定build Dockerfile生成镜像的名称
    image: cloudmusic-rev
    ports:
      - 9999:80
    volumes:
        # 挂载的 Flag
        - "$PWD/flag:/flag"
    networks:
      - net

networks:
    # 配置docker network
    net:
        external:
          name: CTFD